### ISSUE TITLE
Use of Carousal view for on home page

### ISSUE THREAD

**Issue by devoirtechsandip** [egbakou/CreditCardCheckout#1]
This would be my first OSS contribution. Is it okay if I make use of carousal view for credit card slider?

**Comment by egbakou** [comment]
> This would be my first OSS contribution. Is it okay if I make use of carousal view for credit card slider?

Yes you can use it. For my UI, I have used CardsView for credit card slider.

**Comment by devoirtechsandip** [comment]
Thanks for the great UI, I have created pull request with updated screenshots

**Comment by egbakou** [comment]
Thanks for your contribution.
I think that it will be nice to use CarouselView of CardView's nuget package(https://github.com/AndreiMisiukevich/CardView) to do credit card slider.
I say this to avoid the upgrade to the pre-version of Xamarin.Forms.

**Comment by egbakou** [comment]
@devoirtechsandip are you there ?

**Comment by devoirtechsandip** [comment]
Yeah totally respect your decision that.

**Comment by egbakou** [comment]
The fench blog post on this UI design: https://lioncoding.com/2019/10/11/2019-10-11-xamarin-ui-challenge-credit-card-checkout/
@devoirtechsandip , I thank you in my article for your contribution. 🤓
